config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboards#index"
  
  resources :users do
    resources :exercises
  end
  
  resources :dashboards, only: [:index] do
    collection do
      post :search, to: 'dashboards#search'
    end
  end
  
  resources :friendships, only: [:show, :create, :destroy]
  resources :messages, only: [:create]
  
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  
  alias_attribute :workout_details, :workout
  alias_attribute :activity_date, :workout_date
  
  validates :duration_in_min, numericality: { greater_than: 0.0 }
  validates :workout_details, presence: true
  validates :activity_date, presence: true
  
  default_scope { where('workout_date > ?', 7.days.ago).order(workout_date: :desc) }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :exercises
  has_many :friendships
  has_many :friends, through: :friendships, class_name: "User"
  has_one :room
  has_many :messages
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  after_create :create_chatroom
  
  self.per_page = 10
  
  def full_name
    # "#{first_name} #{last_name}"
    [first_name, last_name].join(" ")
  end
  
  def self.search_by_name(name)
    names_array = name.split(' ')
    
    if names_array.size == 1
      where('first_name LIKE ? or last_name LIKE ?',
        "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name LIKE ? or first_name LIKE ? or last_name LIKE ? or last_name LIKE ?',
        "%#{names_array[0]}%", "%#{names_array[1]}%",
        "%#{names_array[0]}%", "%#{names_array[1]}%").order(:first_name)
    end
  end
  
  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) || self == new_friend
  end
  
  def current_friendship(friend)
    friendships.where(friend: friend).first
  end
  
private

  def create_chatroom
    hyphenated_username = self.full_name.split.join('-')
    Room.create(name: hyphenated_username, user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
private

  def current_room
    @room ||= Room.find(session[:current_room]) if session[:current_room]
  end
  
  helper_method :current_room
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @athletes = User.paginate(:page => params[:page])
  end
  
  def search
    @athletes = User.search_by_name(params[:search_name]).paginate(page: params[:page])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  
  def index
    @exercises = current_user.exercises
    @friends = current_user.friends
    set_current_room
    @message = Message.new
    @messages = current_room.messages if current_room
    @followers = Friendship.where(friend_id: current_user.id)
  end
  
  def show
    set_exercise
  end
  
  def new
    @exercise = current_user.exercises.new
  end
  
  def create
    @exercise = current_user.exercises.new(exercise_params)
    if @exercise.save 
      flash[:notice] = "Exercise has been created."
      redirect_to [current_user, @exercise]
    else
      flash.now[:alert] = "Exercise has not been created."
      render :new
    end
  end
  
  def edit
    set_exercise
  end
  
  def update
    set_exercise
    if @exercise.update(exercise_params)
      flash[:notice] = "Exercise has been updated."
      redirect_to [current_user, @exercise]
    else
      flash.now[:alert] = "Exercise has not been updated."
      render :edit
    end
  end
  
  def destroy
    set_exercise
    @exercise.destroy
    flash[:notice] = "Exercise has been deleted."
    redirect_to user_exercises_path(current_user)
  end
  
private

  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end
  
  def exercise_params
    params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
  end
  
  def set_current_room
    if params[:roomId]
      @room = Room.find_by(id: params[:roomId])
    else
      @room = current_user.room
    end
    session[:current_room] = @room.id if @room
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @friend = Friendship.find(params[:id]).friend
    @exercises = @friend.exercises
  end
  
  def create
    friend = User.find(params[:friend_id])
    params[:user_id] = current_user.id
    
    Friendship.create(friendship_params) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end
  
  def destroy
    @friendship = Friendship.find(params[:id])
    if @friendship.destroy
      flash[:notice] = "#{@friendship.friend.full_name} unfollowed."
    else
      flash.now[:alert] = "#{@friendship.friend.full_name} could not be unfollowed."
    end
    redirect_to user_exercises_path(current_user)
  end
  
private

  def friendship_params
    params.permit(:friend_id, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @message = current_user.messages.build(message_params)
    @message.room = current_room
    
    @message.save
    
    redirect_to user_exercises_path current_user
  end
  
private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email,
        :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email,
        :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<div class="jumbotron">
  <h1>Workout Lounge!</h1>
</div>

<p>Show off your workout to your friends and family</p>

<div class="row">
  <div class="col-md-10">
    <h2>List of Members</h2>
    <%= will_paginate @athletes, renderer: BootstrapPagination::Rails, class: "pull-left paginate" %>
  </div>
</div>

<div class="row">
  <% @athletes.each do |athlete| %>
    <div class="col-md-10 well member">
      <%= athlete.full_name %>
      <% if current_user %>
        <%= link_to "Follow", friendships_path(friend_id: athlete.id),
              method: :post, class: "btn btn-success pull-right" \
              unless current_user.follows_or_same?(athlete) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboards/search.html.erb
<div class="row search-result">
  <% @athletes.each do |athlete| %>
    <div class="col-md-10 col-md-offset-2 well member">
      <%= athlete.full_name %>
    </div>
  <% end %>
</div>

<%= will_paginate @athletes, renderer: BootstrapPagination::Rails %>

app/views/exercises/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for([current_user, @exercise],
        :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @exercise.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@exercise.errors.count, "error") %>
          prohibited this exercise from being saved:</h2>
          <ul>
            <% @exercise.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :duration_in_min, "Duration (min)" %>
        </div>
        <div class="col-md-10">
          <%= f.number_field :duration_in_min, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Workout Details" %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :workout, class: "form-control", rows: 10 %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout_date, "Activity Date" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :workout_date, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-success btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/edit.html.erb
<h1 class="text-center">Editing Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to "Back", user_exercises_path(current_user),
          class: "btn btn-default link", id: "back-btn" %>
    </div>
  </div>
</div>

app/views/exercises/index.html.erb
<% content_for(:whole_page) do %>
  
  <div class="col-md-7 col-xs-12">
    <% unless @exercises.empty? %>
      <h1>Listing Exercises</h1>
      
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Duration (min)</th>
            <th>Workout details</th>
            <th>Activity date</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @exercises.each do |exercise| %>
            <tr>
              <td><%= exercise.duration_in_min %></td>
              <td><%= truncate(exercise.workout, length: 100) %></td>
              <td><%= exercise.workout_date %></td>
              <td><%= link_to 'Show', [current_user, exercise] %></td>
              <td><%= link_to 'Edit', [:edit, current_user, exercise] %></td>
              <td><%= link_to 'Destroy', [current_user, exercise],
                          method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      
      <br>
    <% else %>
      <div class="alert alert-danger message-font text-center" role="alert">
        No Workouts Yet
      </div>
      <br>
    <% end %>
    <%= link_to "New Workout", new_user_exercise_path(current_user),
            class: "btn btn-success link" %>
    <%= content_tag :div, "", id: 'chart', data: { workouts: @exercises } %>
  </div>
  
  <div class="col-md-5 col-xs-12">
    <div id="chat-window" class="col-md-12">
      <header class="text-center">Channel: <%= current_room.name %></header>
      
      <div class="col-md-2" id="followers">
        <% @followers.each do |follower| %>
          <%= link_to follower.user.full_name, user_exercises_path(current_user,
                  roomId: follower.user.room.id), class: 'followers' %>
          <br />
        <% end %>
      </div>
      
      <div class="col-md-10" id="messages-box">
        <div id="chat-box" data-channel="rooms" data-room-id=<%= current_room.id %>>
          <% @messages.each do |message| %>
            <%= render partial: "shared/message", locals: { message: message } %>
          <% end %>
        </div>
        <div id="form-box">
          <%= form_for @message do |f| %>
            <%= f.text_field :body, id: "message-field", class: "form-control pull-left" %>
            <%= f.submit 'Post', class: "btn btn-default", id: "post-btn" %>
          <% end %>
        </div>
      </div>
    </div>
    
    <h1 class="text-center">My Friends</h1>
    
    <% @friends.each do |friend| %>
      <div class="col-md-offset-3 col-md-6 friend_name">
        <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
      </div>
      
      <div class="col-md-3">
        <div class="btn-unfollow">
          <%= link_to "Unfollow", friendship_path(current_user.current_friendship(friend)),
                  method: :delete, data: { confirm: "Are you sure?" },
                  class: "btn btn-success link" %>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to "Back", user_exercises_path(current_user),
          class: "btn btn-default link", id: "new-exer-btn" %>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h2 class="show-header">Showing <%= "#{@exercise.user.full_name}'s Workout Details" %></h2>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout Details:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity Date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>
  <br>
  <br>
  <div class="col-xs-12 col-md-10 member">
    <%= link_to 'Back', user_exercises_path(current_user),
        class: "btn btn-success btn-lg link", id: "back-btn" %>
  </div>
</div>

app/views/friendships/show.html.erb
<div class="col-md-8">
  <p id="notice"><%= notice %></p>
  
  <h1><%= @friend.full_name %>'s Exercises</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Duration (min)</th>
        <th>Distance</th>
        <th>Activity date</th>
      </tr>
    </thead>
    
    <tbody>
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.duration_in_min %></td>
          <td><%= truncate(exercise.workout, length: 100) %></td>
          <td><%= exercise.workout_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= content_tag :div, "", id: 'chart', data: {workout: @exercises} %>
  
  <br>
  
  <%= link_to "Back", user_exercises_path(current_user),
          class: "btn btn-success btn-lg link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    
    <%= render 'shared/main' %>
    
    <%= render 'shared/footer' %>
    
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container">
  <div class='row'>
    <div class="col-md-10 text-center">
      <footer role="contentinfo">
        <p><small>Copyright &copy; Paul Deestee</small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="botton" class="navbar-toggle" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Athletes Den", root_path %>
      </div>
      
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
        </ul>
        
        <%= form_tag(search_dashboards_path,
                     class: "navbar-form navbar-left",
                     role: "search") do %>
          <div class="form-group">
            <%= text_field_tag :search_name, nil, placeholder: "Search for friends",
                  class: "form-control" %>
          </div>
          <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %>
        
        <ul class="nav navbar-nav navbar-right">
          <% unless user_signed_in? %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% else %>
            <li><%= link_to "My Lounge", user_exercises_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <div class="navbar-right signed-in-user">
              <div class="navbar-text">
                Signed in as <%= "#{current_user.email}" %>
              </div>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class="<%= content_for(:whole_page) ? 'container-fluid' : 'container' %>">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-centred alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
      <%= yield :whole_page %>
    </div>
  </div>
</div>

app/views/shared/_message.html.erb
<div class="message-row">
  <p class="message-body"><%= message.body %></p>
  <span>"<small><%= message.user.full_name %></small>"</span>
</div>